# Generated by Django 6.0.4 on 2026-05-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
                ('paket', models.CharField(max_length=100)),
                ('status', models.CharField(default='Menunggu', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teknisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=20)),
                ('wilayah', models.CharField(max_length=100)),
            ],
        ),
    ]
