# Generated by Django 6.0.4 on 2026-05-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='status',
            field=models.CharField(default='Menunggu Instalasi', max_length=100),
        ),
    ]
