# Generated by Django 6.0.4 on 2026-05-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0002_alter_pelanggan_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teknisi',
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='no_hp',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='paket',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
