# Generated by Django 6.0.4 on 2026-05-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0003_delete_teknisi_alter_pelanggan_no_hp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='no_hp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
