# Generated by Django 6.0.4 on 2026-06-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0004_alter_pelanggan_no_hp_alter_pelanggan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='status',
            field=models.CharField(choices=[('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Menunggu Verifikasi', 'Menunggu Verifikasi'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Menunggu Pembayaran', max_length=50),
        ),
    ]
