# Generated by Django 6.0.4 on 2026-06-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0005_pelanggan_bukti_pembayaran_alter_pelanggan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='bukti_pembayaran',
            field=models.FileField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
    ]
