# Generated by Django 6.0.4 on 2026-06-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0006_alter_pelanggan_bukti_pembayaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('komentar', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('bukti_pembayaran', models.FileField(blank=True, null=True, upload_to='bukti_pembayaran/')),
            ],
        ),
        migrations.RemoveField(
            model_name='pelanggan',
            name='bukti_pembayaran',
        ),
    ]
