# Generated by Django 6.0.4 on 2026-06-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0007_rating_remove_pelanggan_bukti_pembayaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='bukti_pembayaran',
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='bukti_pembayaran',
            field=models.FileField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
