# Generated by Django 6.0.4 on 2026-06-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0009_rating_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='bukti_pembayaran',
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='struk_pembayaran',
            field=models.TextField(blank=True, null=True),
        ),
    ]
