# Generated by Django 6.0.4 on 2026-06-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0010_remove_pelanggan_bukti_pembayaran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='struk_pembayaran',
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
    ]
